name: 'Setup Common Environment'
description: 'Set up common environment variables for all workflows'
inputs:
  package-name:
    description: 'Swift package name'
    required: false
    default: 'binary-dependencies-manager'
  swift-version:
    description: 'Swift version'
    required: false
    default: '6.1'
  xcode-version:
    description: 'Xcode version'
    required: false
    default: '16.4'
outputs:
  package-name:
    description: 'Swift package name'
    value: ${{ steps.set-env.outputs.package-name }}
  swift-version:
    description: 'Default Swift version'
    value: ${{ steps.set-env.outputs.swift-version }}
  xcode-version:
    description: 'Default Xcode version'
    value: ${{ steps.set-env.outputs.xcode-version }}
runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      id: set-env
      shell: bash
      run: |
        echo "package-name=${{ inputs.package-name }}" >> $GITHUB_OUTPUT
        echo "swift-version=${{ inputs.swift-version }}" >> $GITHUB_OUTPUT
        echo "xcode-version=${{ inputs.xcode-version }}" >> $GITHUB_OUTPUT

        # Also set as environment variables for current job
        echo "PACKAGE_NAME=${{ inputs.package-name }}" >> $GITHUB_ENV
        echo "SWIFT_VERSION=${{ inputs.swift-version }}" >> $GITHUB_ENV
        echo "XCODE_VERSION=${{ inputs.xcode-version }}" >> $GITHUB_ENV
