name: 'Cache Swift Packages'
description: 'Cache Swift Package Manager dependencies and build artifacts'
inputs:
  package-name:
    description: 'Name of the Swift package'
    required: true
  build-system:
    description: 'Build system being used (swift or xcodebuild)'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: |
          .build/artifacts
          .build/checkouts
          .build/repositories
          .build/workspace-state.json
          DerivedData/${{ inputs.package-name }}/SourcePackages
          ~/Library/Caches/org.swift.swiftpm/
          ~/.cache/org.swift.swiftpm/
        key: ${{ runner.os }}-${{ inputs.build-system }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.build-system }}-spm-
