name: Test

on:
  pull_request:
    branches:
      - main
      - chore/refactor

jobs:
  test:
    env:
      package_name: binary-dependencies-manager

    strategy:
      matrix:
        include:
          - os: macos-15
            build-system: swift
            swift-version: '6.1'
            xcode-version: '16.4'
          - os: ubuntu-latest
            build-system: swift
            swift-version: '6.1'
          - os: macos-15
            build-system: xcodebuild
            xcode-version: '16.4'

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Select Swift Version
      uses: ./.github/workflows/templates/select-swift-version.yaml
      with:
        xcode-version: ${{ matrix.xcode-version }}
        swift-version: ${{ matrix.swift-version }}

    - name: Cache Swift Packages
      uses: ./.github/workflows/templates/swift-cache.yaml
      with:
        package-name: ${{ env.package_name }}
        build-system: ${{ matrix.build-system }}

    - name: Build with Swift Package Manager
      if: matrix.build-system == 'swift'
      run: swift build

    - name: Test with Swift Package Manager
      if: matrix.build-system == 'swift'
      run: swift test

    - name: Build with Xcodebuild
      if: matrix.build-system == 'xcodebuild'
      run: |
        xcodebuild \
          -scheme ${{ env.package_name }} \
          -destination 'platform=macOS' \
          -derivedDataPath DerivedData \
          -collect-test-diagnostics never \
          RUN_CLANG_STATIC_ANALYZER=NO \
          COMPILER_INDEX_STORE_ENABLE=NO \
          build-for-testing

    - name: Test with Xcodebuild
      if: matrix.build-system == 'xcodebuild'
      run: |
        xcodebuild \
          -scheme ${{ env.package_name }} \
          -destination 'platform=macOS' \
          -derivedDataPath DerivedData \
          -collect-test-diagnostics never \
          RUN_CLANG_STATIC_ANALYZER=NO \
          COMPILER_INDEX_STORE_ENABLE=NO \
          test
